api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r'pokemons', views.PokemonViewSet)
router.register(r'entrenadores', views.EntrenadorViewSet)


urlpatterns = [
    path('', include(router.urls))   
    
    
]

lab8/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from . import settings 
from django.urls import path, include
from oauth2_provider import urls as oauth2_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pokedex.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('o/', include(oauth2_urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pokedex/urls.py
from django.urls import path

from . import views

app_name = "pokedex"

urlpatterns = [
    path("", views.index, name="index"),
    path("pokemon/<int:id>/", views.pokemon, name="detail"),
    path("pokemon/add/", views.add_pokemon, name="add_pokemon"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("edit_pokemon/<int:id>/",views.edit_pokemon,name="edit_pokemon"),
    path("delete_pokemon/<int:id>/",views.delete_pokemon,name="delete_pokemon"),
    
    path("entrenadores/", views.lista_entrenadores, name="lista_entrenadores"),
    path("entrenadores/add/", views.add_entrenador, name="add_entrenador"),
    path("entrenadores/<int:id>/", views.edit_entrenador, name="edit_entrenador"),
    path("entrenadores/<int:id>/delete/", views.delete_entrenador, name="delete_entrenador"),
]

api/models.py
from django.db import models

# Create your models here.

pokedex/models.py
from django.db import models

class Entrenador(models.Model):
    name = models.CharField(max_length=15, null=False)
    lastname = models.CharField(max_length=15, null=False)
    level = models.IntegerField(null=False)
    picture = models.ImageField(upload_to="entrenador_images", null=True)
    
    def __str__(self):
        return f"{self.name} {self.lastname}"


class Pokemon(models.Model):
    name = models.CharField(max_length=40, null=False)
    type = models.CharField(max_length=30, null=False)
    weight = models.IntegerField(null=False)
    height = models.IntegerField(null=False)
    picture = models.ImageField(upload_to="pokemon_images", null=True)
    entrenador = models.ForeignKey(Entrenador, on_delete=models.SET_NULL, null=True, blank=True)

    
    def __str__(self):
        return self.name 
    

pokedex/forms.py
from django import forms
from .models import Pokemon
from .models import Entrenador

class PokemonForm(forms.ModelForm):
    class Meta:
        model = Pokemon
        fields = ['name', 'type', 'weight', 'height', 'picture', 'entrenador']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Charmander'}),
            'type': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Fuego'}),
            'weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'height': forms.NumberInput(attrs={'class': 'form-control'}),
            'picture': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'id' : 'image_field',
            }),
            'entrenador': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'entrenador': 'Asignar a Entrenador',
        }

class EntrenadorForm(forms.ModelForm):
    class Meta:
        model = Entrenador
        fields = ['name', 'lastname', 'level', 'picture']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ash'}),
            'lastname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ketchum'}),
            'level': forms.NumberInput(attrs={'class': 'form-control'}),
            'picture': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'id' : 'image_field',
            }),
        }

api/views.py
from rest_framework import viewsets
from pokedex.models import Pokemon
from .serializers import PokemonSerializer
from pokedex.models import Entrenador
from .serializers import EntrenadorSerializer
from oauth2_provider.contrib.rest_framework import OAuth2Authentication, TokenHasScope
from rest_framework.permissions import IsAuthenticated, AllowAny

class PokemonViewSet(viewsets.ModelViewSet):
    queryset = Pokemon.objects.order_by('name')
    serializer_class = PokemonSerializer
    
    authentication_classes = [OAuth2Authentication]
    required_scopes = ['write']
    
    def get_permissions(self):
        if self.request.method in ['POST', 'PUT', 'PATCH', 'DELETE']:
            return [IsAuthenticated(), TokenHasScope()]
        return [AllowAny()]
    
    
    
class EntrenadorViewSet(viewsets.ModelViewSet):
    queryset = Entrenador.objects.all()
    serializer_class = EntrenadorSerializer
    
    authentication_classes = [OAuth2Authentication]
    permission_classes = [TokenHasScope]

pokedex/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template import loader
from .models import Pokemon
from .forms import PokemonForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from .models import Entrenador
from .forms import EntrenadorForm


def index(request):
    pokemons = Pokemon.objects.order_by('name')
    template = loader.get_template('index.html')
    return HttpResponse(template.render({'pokemons': pokemons}, request))

def pokemon(request,id: int):
    pokemon = Pokemon.objects.get(pk=id)
    template = loader.get_template('display_pokemon.html')
    context = {
        'pokemon': pokemon
    }
    return HttpResponse(template.render(context, request))

@login_required
def add_pokemon(request):
    if request.method == 'POST':
        form = PokemonForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('pokedex:index')
        
    else:
        form = PokemonForm()
            
    return render (request, 'pokemon_form.html', {'form': form})

def edit_pokemon(request, id: int):
    pokemon = Pokemon.objects.get(pk=id)

    if request.method == 'POST':
        form = PokemonForm(request.POST, request.FILES, instance=pokemon)
        if form.is_valid():
            form.save()
            return redirect('pokedex:index')
    else:
        form = PokemonForm(instance=pokemon)

    return render(request, 'pokemon_form.html', {'form': form})

def delete_pokemon(request, id: int):
    pokemon = Pokemon.objects.get(pk=id)
    pokemon.delete()
    return redirect('pokedex:index')


class CustomLoginView(LoginView):
    template_name = "login_form.html"

def lista_entrenadores(request):
    entrenadores = Entrenador.objects.all()
    template = loader.get_template('lista_entrenadores.html')
    return HttpResponse(template.render({'entrenadores': entrenadores}, request))

def add_entrenador(request):
    if request.method == 'POST':
        form = EntrenadorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('pokedex:lista_entrenadores')
    else:
        form = EntrenadorForm()
    
    template = loader.get_template('form_entrenador.html')
    return HttpResponse(template.render({'form': form}, request))


def edit_entrenador(request, id: int):
    entrenador = Entrenador.objects.get(pk=id)

    if request.method == 'POST':
        form = EntrenadorForm(request.POST, request.FILES, instance=entrenador)
        if form.is_valid():
            form.save()
            return redirect('pokedex:lista_entrenadores')
    else:
        form = EntrenadorForm(instance=entrenador)
    
    template = loader.get_template('form_entrenador.html')
    return HttpResponse(template.render({'form': form}, request))


def delete_entrenador(request, id: int):
    entrenador = Entrenador.objects.get(pk=id)
    entrenador.delete()
    return redirect('pokedex:lista_entrenadores')

pokedex/templates/base.html
{% load static %}
<html>
    <head>
        <title>{% block title %}{% endblock title %}</title>
        <link href="{% static "bootstrap.min.css" %}" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    </head>
    <body>
        <div class="container">
            <div class="bg-primary text-white p-4 text-center">
                <img src="{% static "logo.svg" %}" alt="logo-pokedex" class="img-fluid">
            </div>

           <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url "pokedex:index" %}"><i class="fa-solid fa-house"></i></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarScroll">
                        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                            {% if user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'pokedex:add_pokemon' %}">Añadir Pokemon</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'pokedex:lista_entrenadores' %}">Ver entrenadores</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesión</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'pokedex:login' %}">Iniciar sesión</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'pokedex:lista_entrenadores' %}">Ver entrenadores</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>

            {%block content %}{% endblock content %}
        </div>
    </body>
</html>

pokedex/templates/display_pokemon.html
{% extends "base.html" %}
{% block title %}{{ pokemon.name|capfirst }} - Detalles{% endblock title %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow">
                {% if pokemon.picture %}
                    <img src="{{ pokemon.picture.url }}" class="card-img-top mx-auto d-block" style="max-width: 300px;" alt="{{ pokemon.name }}">

                {% else %}
                    <img src="https://via.placeholder.com/500x300.png?text=Sin+Imagen" class="card-img-top" alt="No hay imagen disponible">
                {% endif %}

                <div class="card-body">
                    <h2 class="card-title text-center">{{ pokemon.name|capfirst }}</h2>

                    <ul class="list-group list-group-flush my-3">
                        <li class="list-group-item"><strong>Tipo:</strong> {{ pokemon.type }}</li>
                        <li class="list-group-item"><strong>Peso:</strong> {{ pokemon.weight }} Kg</li>
                        <li class="list-group-item"><strong>Altura:</strong> {{ pokemon.height }} cm</li>
                        {% if pokemon.entrenador %}
                            <li class="list-group-item">
                                <strong>Entrenador:</strong> 
                                {{ pokemon.entrenador.name }} {{ pokemon.entrenador.lastname }} 
                                (Nivel {{ pokemon.entrenador.level }})
                            </li>
                        {% endif %}
                    </ul>

                    <div class="text-center">
                        <a href="{% url 'pokedex:index' %}" class="btn btn-outline-primary mt-2">Volver al listado</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

pokedex/templates/form_entrenador.html
{% extends "base.html" %}
{% block title %}Formulario de Entrenador{% endblock title %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
     <a href="{% url 'pokedex:lista_entrenadores' %}" class="btn btn-secondary">Regresar</a>
</form>
{% endblock content %}

pokedex/templates/index.html
{% extends "base.html" %}
{% block title %}Listado de Pokemon{% endblock title %}
{% block content %}
<p class="p-2">Bienvenidos a mi Pokedex</p>

{% if user.is_authenticated %}
    <a href="{% url 'pokedex:add_pokemon' %}" class="btn btn-success mb-3">
        <i class="fa-solid fa-user-plus"></i> Añadir Pokemon
    </a>
{% endif %}

<ul class="list-group">
    <div class="row">
        {% for pokemon in pokemons %}
        <div class="col-sm-6 col-md-4 col-lg-3 mb-4">
            <div class="card h-100">
                {% if pokemon.picture %}
                    <img src="{{ pokemon.picture.url }}" alt="{{ pokemon.name }}" class="card-img-top">
                {% else %}
                    <p>No hay imagen disponible</p>
                {% endif %}

                
                <div class="card-body">
                    <h5 class="card-title">{{ pokemon.name }}</h5>
                    <p class="card-text">
                        Peso: {{ pokemon.weight }} | Altura: {{ pokemon.height }}
                        {% if pokemon.entrenador %}
                            <p class="card-text">
                                Entrenador: {{ pokemon.entrenador.name }} {{ pokemon.entrenador.lastname }}
                            </p>
                        {% endif %}

                    </p>
                    <a class="btn btn-primary" href="{% url 'pokedex:detail' pokemon.id %}" role="button">
                        <i class="fa-solid fa-eye"></i>
                    </a>
                    {% if user.is_authenticated %}
                    <a class="btn btn-secondary" href="{% url 'pokedex:edit_pokemon' pokemon.id %}" role="button">
                        <i class="fa-solid fa-pencil"></i>
                    </a>
                    <a class="btn btn-danger" href="{% url 'pokedex:delete_pokemon' pokemon.id %}" role="button">
                        <i class="fa-solid fa-trash"></i>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</ul>

{% endblock content %}

pokedex/templates/lista_entrenadores.html
{% extends "base.html" %}
{% block title %}Lista de Entrenadores{% endblock title %}

{% block content %}
<br>

{% if user.is_authenticated %}
    <a href="{% url 'pokedex:add_entrenador' %}" class="btn btn-success mb-3">
        <i class="fa-solid fa-user-plus"></i> Crear Entrenador
    </a>
{% endif %}

<div class="row">
    {% for entrenador in entrenadores %}
    <div class="col-sm-6 col-md-4 col-lg-3 mb-4">
        <div class="card h-100">
            <div class="card-body">
                {% if entrenador.picture %}
                    <img src="{{ entrenador.picture.url }}" alt="{{ entrenador.name }}" class="img-thumbnail">
                {% else %}
                     <p>No hay imagen disponible</p>
                {% endif %}
                <h5 class="card-title">{{ entrenador.name }} {{ entrenador.lastname }}</h5>
                <p class="card-text">Nivel: {{ entrenador.level }}</p>

                {% if user.is_authenticated %}
                <a href="{% url 'pokedex:edit_entrenador' entrenador.id %}" class="btn btn-secondary">
                    <i class="fa-solid fa-pencil"></i> Editar
                </a>
                <a href="{% url 'pokedex:delete_entrenador' entrenador.id %}" class="btn btn-danger">
                    <i class="fa-solid fa-trash"></i> Eliminar
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

pokedex/templates/login_form.html
{% extends "base.html" %}

{% block title %}Ingreso al sistema{% endblock title %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <div>
                <label for="username">Usuario</label>
                <input type="text" name="username" id="username" class="form-control" />
            </div>
            <div>
                <label for="password">Contraseña</label>
                <input type="password" name="password" id="password" class="form-control" />
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Ingresar</button>
            <a href="{% url 'pokedex:index' %}" class="btn btn-secondary">Regresar</a>
        </div>
    </div>
</form>
{% endblock content %}

pokedex/templates/pokemon_form.html
{% extends "base.html" %}
{% block title %}Formulario de Pokemon{% endblock title %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_div }}
    <button type="submit" class="btn btn-primary">Guardar</button>
     <a href="{% url 'pokedex:index' %}" class="btn btn-secondary">Regresar</a>
</form>
{% endblock content %}